package com.example.productapi;

import java.net.URI;
import java.util.List;

import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.OpenAPIDefinition;
import org.eclipse.microprofile.openapi.annotations.enums.SecuritySchemeType;
import org.eclipse.microprofile.openapi.annotations.info.Info;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.security.SecurityRequirement;
import org.eclipse.microprofile.openapi.annotations.security.SecurityScheme;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;

import io.quarkus.security.Authenticated;
import jakarta.annotation.security.RolesAllowed;
import jakarta.transaction.Transactional;
import jakarta.validation.Valid;
import jakarta.ws.rs.BadRequestException;
import jakarta.ws.rs.NotFoundException;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.WebApplicationException;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

@Path("/api/products")
@Authenticated
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@OpenAPIDefinition(info = @Info(title = "Products API", version = "1.0.0", description = "Authenticated product catalog API"))
@SecurityScheme(securitySchemeName = "bearerAuth", type = SecuritySchemeType.HTTP, scheme = "bearer", bearerFormat = "JWT")
@Tag(name = "Products", description = "Product catalog operations")
@SecurityRequirement(name = "bearerAuth")
public class ProductResource {
    private final ProductRepository products;

    public ProductResource(ProductRepository products) {
        this.products = products;
    }

    @GET
    @RolesAllowed({"user", "admin"})
    @Operation(summary = "List products", description = "Returns all products. Requires the user or admin role.")
    @APIResponse(responseCode = "200", description = "Products returned successfully")
    @APIResponse(responseCode = "401", description = "Missing or invalid access token")
    @APIResponse(responseCode = "403", description = "Insufficient role")
    public List<Product> list() {
        return products.listAll();
    }

    @GET
    @Path("/{id}")
    @RolesAllowed({"user", "admin"})
    @Operation(summary = "Get a product", description = "Returns the product with the specified ID. Requires the user or admin role.")
    @APIResponse(responseCode = "200", description = "Product returned successfully")
    @APIResponse(responseCode = "401", description = "Missing or invalid access token")
    @APIResponse(responseCode = "403", description = "Insufficient role")
    @APIResponse(responseCode = "404", description = "Product not found")
    public Product get(@PathParam("id") Long id) {
        return products.findByIdOptional(id).orElseThrow(NotFoundException::new);
    }

    @POST
    @Transactional
    @RolesAllowed("admin")
    @Operation(summary = "Create a product", description = "Creates a product. The ID is generated by the server. Requires the admin role.")
    @APIResponse(responseCode = "201", description = "Product created successfully")
    @APIResponse(responseCode = "400", description = "Invalid product or client-supplied ID")
    @APIResponse(responseCode = "401", description = "Missing or invalid access token")
    @APIResponse(responseCode = "403", description = "Admin role required")
    @APIResponse(responseCode = "409", description = "SKU already exists")
    public Response create(@Valid Product product) {
        if (product.getId() != null) {
            throw new BadRequestException("id is generated by the server");
        }
        ensureSkuIsAvailable(product.getSku(), null);
        products.persist(product);
        URI location = URI.create("/api/products/" + product.getId());
        return Response.created(location).entity(product).build();
    }

    @PUT
    @Path("/{id}")
    @Transactional
    @RolesAllowed("admin")
    @Operation(summary = "Update a product", description = "Updates a product. A supplied body ID must match the path ID. Requires the admin role.")
    @APIResponse(responseCode = "200", description = "Product updated successfully")
    @APIResponse(responseCode = "400", description = "Invalid product or body ID does not match path ID")
    @APIResponse(responseCode = "401", description = "Missing or invalid access token")
    @APIResponse(responseCode = "403", description = "Admin role required")
    @APIResponse(responseCode = "404", description = "Product not found")
    @APIResponse(responseCode = "409", description = "SKU already exists")
    public Product update(@PathParam("id") Long id, @Valid Product input) {
        Product product = products.findByIdOptional(id).orElseThrow(NotFoundException::new);
        if (input.getId() != null && !input.getId().equals(id)) {
            throw new BadRequestException("body id must match the path id");
        }
        ensureSkuIsAvailable(input.getSku(), id);
        product.setNombre(input.getNombre());
        product.setPrecio(input.getPrecio());
        product.setStock(input.getStock());
        product.setSku(input.getSku());
        return product;
    }

    @DELETE
    @Path("/{id}")
    @Transactional
    @RolesAllowed("admin")
    @Operation(summary = "Delete a product", description = "Deletes a product by ID. Requires the admin role.")
    @APIResponse(responseCode = "204", description = "Product deleted successfully")
    @APIResponse(responseCode = "401", description = "Missing or invalid access token")
    @APIResponse(responseCode = "403", description = "Admin role required")
    @APIResponse(responseCode = "404", description = "Product not found")
    public Response delete(@PathParam("id") Long id) {
        if (!products.deleteById(id)) {
            throw new NotFoundException();
        }
        return Response.noContent().build();
    }

    private void ensureSkuIsAvailable(String sku, Long currentId) {
        products.findBySku(sku).ifPresent(existing -> {
            if (!existing.getId().equals(currentId)) {
                throw new WebApplicationException("sku already exists", Response.Status.CONFLICT);
            }
        });
    }
}