package com.example.productapi;

import java.net.URI;
import java.util.List;

import io.quarkus.security.Authenticated;
import jakarta.annotation.security.RolesAllowed;
import jakarta.transaction.Transactional;
import jakarta.validation.Valid;
import jakarta.ws.rs.BadRequestException;
import jakarta.ws.rs.NotFoundException;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.WebApplicationException;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

@Path("/api/products")
@Authenticated
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class ProductResource {
    private final ProductRepository products;

    public ProductResource(ProductRepository products) {
        this.products = products;
    }

    @GET
    @RolesAllowed({"user", "admin"})
    public List<Product> list() {
        return products.listAll();
    }

    @GET
    @Path("/{id}")
    @RolesAllowed({"user", "admin"})
    public Product get(@PathParam("id") Long id) {
        return products.findByIdOptional(id).orElseThrow(NotFoundException::new);
    }

    @POST
    @Transactional
    @RolesAllowed("admin")
    public Response create(@Valid Product product) {
        if (product.getId() != null) {
            throw new BadRequestException("id is generated by the server");
        }
        ensureSkuIsAvailable(product.getSku(), null);
        products.persist(product);
        URI location = URI.create("/api/products/" + product.getId());
        return Response.created(location).entity(product).build();
    }

    @PUT
    @Path("/{id}")
    @Transactional
    @RolesAllowed("admin")
    public Product update(@PathParam("id") Long id, @Valid Product input) {
        Product product = products.findByIdOptional(id).orElseThrow(NotFoundException::new);
        if (input.getId() != null && !input.getId().equals(id)) {
            throw new BadRequestException("body id must match the path id");
        }
        ensureSkuIsAvailable(input.getSku(), id);
        product.setNombre(input.getNombre());
        product.setPrecio(input.getPrecio());
        product.setStock(input.getStock());
        product.setSku(input.getSku());
        return product;
    }

    @DELETE
    @Path("/{id}")
    @Transactional
    @RolesAllowed("admin")
    public Response delete(@PathParam("id") Long id) {
        if (!products.deleteById(id)) {
            throw new NotFoundException();
        }
        return Response.noContent().build();
    }

    private void ensureSkuIsAvailable(String sku, Long currentId) {
        products.findBySku(sku).ifPresent(existing -> {
            if (!existing.getId().equals(currentId)) {
                throw new WebApplicationException("sku already exists", Response.Status.CONFLICT);
            }
        });
    }
}