quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=products
quarkus.datasource.password=products
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/products
quarkus.hibernate-orm.schema-management.strategy=update

quarkus.oidc.auth-server-url=http://localhost:8080/realms/dev-realm
quarkus.oidc.client-id=backend-api
quarkus.oidc.application-type=service
quarkus.oidc.token.audience=backend-api
quarkus.oidc.roles.role-claim-path=realm_access/roles

quarkus.http.port=8081
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:8000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Authorization,Content-Type

%test.quarkus.smallrye-openapi.enabled=true
%test.quarkus.swagger-ui.enabled=true
%dev.quarkus.smallrye-openapi.enabled=true
%dev.quarkus.swagger-ui.enabled=true
%prod.quarkus.smallrye-openapi.enabled=false
%prod.quarkus.swagger-ui.enabled=false